"""add card info to user payment methods

Revision ID: 07e129b35220
Revises: 101dc5c60e8b
Create Date: 2026-01-03 00:00:25.728406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e129b35220'
down_revision = '101dc5c60e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_last4', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_brand', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_payment_methods', schema=None) as batch_op:
        batch_op.drop_column('card_brand')
        batch_op.drop_column('card_last4')

    # ### end Alembic commands ###
