"""Add constraint to overdue_charges.payment_status

Revision ID: 101dc5c60e8b
Revises: 8afa4be9834f
Create Date: 2025-12-28 02:01:33.284659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '101dc5c60e8b'
down_revision = '8afa4be9834f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               nullable=False)

    with op.batch_alter_table('overdue_charges', schema=None) as batch_op:
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.drop_constraint('overdue_charges_payment_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_overdue_charges_payment_id'), ['payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_overdue_charges_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_overdue_charges_refund_id'), ['refund_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overdue_charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_overdue_charges_refund_id'))
        batch_op.drop_index(batch_op.f('ix_overdue_charges_payment_status'))
        batch_op.drop_index(batch_op.f('ix_overdue_charges_payment_id'))
        batch_op.create_unique_constraint('overdue_charges_payment_id_key', ['payment_id'])
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('hours',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
