"""make webhook_token required and remove webhook_secret

Revision ID: 6118521bd74a
Revises: 0aa2b28d6f9b
Create Date: 2025-12-27 21:19:19.693973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6118521bd74a'
down_revision = '0aa2b28d6f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
        # 1️⃣ webhook_token → NOT NULL
        op.alter_column(
            "owner_payment_accounts",
            "webhook_token",
            existing_type=sa.String(length=128),
            nullable=False,
        )

        # 2️⃣ unique constraint
        op.create_unique_constraint(
            "uq_owner_payment_accounts_webhook_token",
            "owner_payment_accounts",
            ["webhook_token"],
        )

def downgrade():
    # вернуть webhook_secret
    op.add_column(
        "owner_payment_accounts",
        sa.Column("webhook_secret", sa.String(length=255), nullable=True),
    )

    op.drop_constraint(
        "uq_owner_payment_accounts_webhook_token",
        "owner_payment_accounts",
        type_="unique",
    )

    op.alter_column(
        "owner_payment_accounts",
        "webhook_token",
        existing_type=sa.String(length=128),
        nullable=True,
    )
