"""user_payment_methods + booking FK

Revision ID: 8afa4be9834f
Revises: 6118521bd74a
Create Date: 2025-12-27 23:50:30.096905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afa4be9834f'
down_revision = '6118521bd74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_bookings_payment_account_id'), ['payment_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.drop_constraint('fk_bookings_payment_account', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_payment_methods', ['payment_method_id'], ['id'])
        batch_op.create_foreign_key(None, 'owner_payment_accounts', ['payment_account_id'], ['id'])

    with op.batch_alter_table('owner_payment_accounts', schema=None) as batch_op:
        batch_op.alter_column('webhook_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_index('idx_owner_payment_owner')
        batch_op.drop_index('idx_owner_payment_provider')
        batch_op.drop_constraint('uq_owner_provider_active', type_='unique')
        batch_op.drop_index('ix_owner_payment_accounts_webhook_token')
        batch_op.create_index(batch_op.f('ix_owner_payment_accounts_webhook_token'), ['webhook_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_payment_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_payment_accounts_webhook_token'))
        batch_op.create_index('ix_owner_payment_accounts_webhook_token', ['webhook_token'], unique=False)
        batch_op.create_unique_constraint('uq_owner_provider_active', ['owner_id', 'provider', 'is_active'])
        batch_op.create_index('idx_owner_payment_provider', ['provider'], unique=False)
        batch_op.create_index('idx_owner_payment_owner', ['owner_id'], unique=False)
        batch_op.alter_column('webhook_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_bookings_payment_account', 'owner_payment_accounts', ['payment_account_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_bookings_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_payment_account_id'))
        batch_op.drop_column('payment_method_id')

    # ### end Alembic commands ###
